### PR TITLE
feat: add sd-jwt issuer support and e2e test

### PR DESCRIPTION
**Pull request by TimoGlastra**
This PR builds on top of https://github.com/Sphereon-Opensource/OID4VCI/pull/78, and adds support for issuance side for sd-jwt vcs as well as adds an e2e test using sd-jwt vcs

~~Dependant on https://github.com/Sphereon-Opensource/SSI-SDK/pull/145 to be merged and released~~

### CODE REVIEW

**Comment by TimoGlastra** [comment]
Updates the PR based on the move of the SD-jWT profile from HAIP to OID4VCI: https://github.com/openid/OpenID4VCI/pull/128

**Comment by TimoGlastra** [comment]
Updated the PR with the release of `@sphereon/ssi-types`, should be ready to merge now @nklomp

**Comment by TimoGlastra** [comment]
Hey @nklomp do you have by any chance some time to merge and release this PR this week? It's beginning to be a blocker on our side for finishing the OID4VCI integration in AFJ

**Review by nklomp — APPROVED** [review]
LGTM, thanks

**Pull request merged**
