### PR TITLE
fix: seconds to ms

### PR DESCRIPTION
**Pull request by TimoGlastra**
another fix related to milliseconds vs seconds

### CODE REVIEW

**Comment by TimoGlastra** [comment]
@nklomp could you take a look at this PR?

**Comment by nklomp** [comment]
Yeah, need to have a closer look into it. Because I wasn't entirely sure about it if I remember correctly.

**Comment by nklomp** [comment]
To be clear it revolved more around also renaming the first part or not. I only quickly looked at it a few days ago from mobile phone

**Review by nklomp — APPROVED** [review]

**Comment by nklomp** [comment]
Made a small change. The createdAt from the state manager is in milliseconds. The expiration arguments and JWT claims are in seconds. So the first change IMO was incorrect. Changed it to divide the createdAt by 1000 to convert it to seconds. Then add the tokenExpiresIn and compare that to iat

````typescript
iat > (createdAt/1000 + tokenExpiresIn)
````

**Pull request merged**
